### ISSUE TITLE
Both scrappers: Better initial support

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#11]
For players with a initial in their name these should be attached to the end of the first name instead of the start of the second name, can this be changed? 

Example player: https://www.eliteprospects.com/player/312222/nikita-o.-popugayev

First name would be Nikita O.

**Comment by colinrsmall** [comment]
Fixed in 6ae6fdd, 8b4766c

**Comment by xECK29x** [comment]
Might need to be adjusted, has issues with first names with initials  (ex: https://www.eliteprospects.com/player/9735/t.j.-trevelyan)
