### ISSUE TITLE
Roster Scraper: Players with no valid position set

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#12]
For players with no valid position attained from EP data due to incomplete records, I would like these ignored entirely (maybe use same opt-out switch for invalid DOB due to incomplete date).

Example player: https://www.eliteprospects.com/player/521643/jens-pedersen

This will result in all positions being set to 1 which is invalid for the game.

**Comment by colinrsmall** [comment]
F/D setting all positions to 1 might be a bug - I have players with incomplete positions randomized, so a player with F will randomly be assigned C, LW, RW, LW/RW, etc. Do you want to me get rid of the randomization?

**Comment by xECK29x** [comment]
No the randomization is fine it's the players getting set to all 1's.

**Comment by colinrsmall** [comment]
I don't see the problem with Jens Pedersen - the scraper seems to set his position correctly. I added a check to skip players who have all 1 positions though.
