### ISSUE TITLE
Roster scraper: NHL contracts not being ignored properly

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#13]
I noticed NHL contracts are not being picked up properly by the scraper when the option to ignore them is enabled.  To reproduce run a test pulling the 2021-22 AHL rosters, there are quite a number of NHL contracted players in that result.

**Comment by colinrsmall** [comment]
The way the setting works is that sets the team playing to the NHL team if a player has an NHL contract. It doesn't ignore those players, but I can make that an option if you'd like.

**Comment by xECK29x** [comment]
Oh yes that is what I assumed it was doing, anything contracted to an NHL team, regardless of where they are playing should be ignored with that option enabled.

**Comment by colinrsmall** [comment]
Alright. I might make that a separate option since I think the way it currently works was a specifically requested function.

**Comment by colinrsmall** [comment]
Changed in 39feba5
