### ISSUE TITLE
Might need to be adjusted, has issues with first names with initials  (ex: https://www.eliteprospects.com/player/9735/t.j.-trevelyan)

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#14]
Might need to be adjusted, has issues with first names with initials  (ex: https://www.eliteprospects.com/player/9735/t.j.-trevelyan)

_Originally posted by @xECK29x in https://github.com/colinrsmall/ehm_roster_tools/issues/11#issuecomment-878706850_

**Comment by colinrsmall** [comment]
Fixed in 0d25ecf
