### ISSUE TITLE
Roster Scrapper: Use it to build Extra_config entries for FUTURE_TRANSFERS

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#16]
Reference Discord PM:

Have an interesting use case for the roster scrapper, I would love to use it to be able to popuate and mass-update NCAA, NCAA DIII or USports future comittments (which are kept in the extra config
with EP you can look at future classes for schools: https://www.eliteprospects.com/team/452/univ.-of-wisconsin/2022-2023
Univ. of Wisconsin at eliteprospects.com
Univ. of Wisconsin hockey team page with roster, stats, transactions at Eliteprospects.com

if you go to a player profile you can see they are committed: https://www.eliteprospects.com/player/486534/boston-buckberger
Boston Buckberger at eliteprospects.com
Eliteprospects.com hockey player profile of Boston Buckberger, 2003-06-01 Saskatoon, SK, CAN Canada. Most recently in the AJHL with Brooks Bandits. Complete player biography and stats.

I would love to be able to scrape the next 4 future classes and put them in the format for the extra_config, this would save me a TON of time
#University of Massachusetts-Amherst Minutemen
"FUTURE_TRANSFER" "Ryan" "Ufko" "Chicago Steel" "University of Massachusetts-Amherst Minutemen" 30 6 2022 0 0 4
if we can get the scrapper to just write a text file in that format for each school/future commit that would be awesome, then I can just copy/paste that block into the extra_config
1.5 added support where the source team doesn't have to match in the DB, it should be accurate but it can basically be set to anything, but I would just set it to the current team for the player
let me know if you want a Github issue post for this, no rush on it at all, its just one of those things that is a pain in the ass to maintain

**Comment by colinrsmall** [comment]
I think I built this for you a while ago and forgot to close the issue. Is the Future Commit Scraper still working?

**Comment by xECK29x** [comment]
Yes this is working I think at least 90% of the time, good to close this out!
