### ISSUE TITLE
Change of logic for dealing with "Junior" contracts

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#2]
"Junior" contracts where a junior player is signed to a specific type of contract to allow them to play for the parent club are not fully supported by EHM. To compensate we place these players contracted to the U20 team and place them on loan to the parent club. When the scraper comes across a contract like this (designated by 'Junior', example: https://www.eliteprospects.com/player/112413/adam-raska), I would like to see the scraper add ' U20' to the club contracted team.

Thanks!

**Comment by colinrsmall** [comment]
Fixed in 3f448be
