### ISSUE TITLE
Roster Scraper: Draft classes not pulling "non contracted" 

### ISSUE THREAD

**Issue by flinch44** [colinrsmall/ehm_roster_tools#21]
Before latest patch, when scraping a draft class all players drafted would be printed out on the sheet, and if not contracted during selected season would be left with a blank for "Club Contracted"

Currently the scraper seems to only pull players active during the season selected regardless of options selected. Would be great to have the option to scrape both honestly.

**Comment by colinrsmall** [comment]
Oops, forget to turn off the debug output I was using that was skipping those players. Fixed now :)
