### ISSUE TITLE
Roster Scraper:  Issue pulling club playing/contracted data for 2021-22 contracts

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#23]
It looks like the roster scraper is having issues pulling player details for club contracted/playing for 2021-22 for some of the Slovak leagues, I have not tried any others but it could be due to a page element change recently. 

Attempting to pull contracts for: 

leagues:
https://www.eliteprospects.com/league/slovakia2,https://www.eliteprospects.com/league/slovakia3,https://www.eliteprospects.com/league/slovakia-u20,https://www.eliteprospects.com/league/slovakia-u18

season:
2021-22
contract_expiry_prefix:
30.4.XXXX
show_error_links:

make_junior_contracts_u20:

scrape_international_games:

skip_players_with_blank_dobs:

use_google_drive:

calculate_remaining_eligible_years:

leagues_for_eligibility:
USports NCAA ACHA
nhl_contracts:

Skip players with NHL contracts

**Comment by xECK29x** [comment]
Still having notable issues for some clubs/leagues, Slovakia 2.Liga is one: https://www.eliteprospects.com/league/slovakia3

**Comment by colinrsmall** [comment]
Just ran on Slovakia3, but I'm not seeing this issue on the scraper. Can you double check?

**Comment by xECK29x** [comment]
Getting an error on every player:

Players: 1%
4/466 [00:23<44:45, 5.81s/it]
Traceback (most recent call last):
  File "<ipython-input-17-0acbe3268e8d>", line 60, in scrape
    first_name, last_name, team, league, dob, birth_place, primary_nation, secondary_nation, declared_nation, position, height, weight, shoots, contract_expiry, contracted_team, join_date, intl_games, intl_g, intl_a = scrape_player_page(link)
  File "<ipython-input-15-a36bb93fcbbf>", line 344, in scrape_player_page
    first_name, last_name = get_name(player_page)
  File "<ipython-input-15-a36bb93fcbbf>", line 16, in get_name
    name = name = player_page.find('div', class_='ep-entity-header__name').text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
Missing player information for: https://www.eliteprospects.com/player/227338/matej-crkon
Traceback (most recent call last):
  File "<ipython-input-17-0acbe3268e8d>", line 60, in scrape
    first_name, last_name, team, league, dob, birth_place, primary_nation, secondary_nation, declared_nation, position, height, weight, shoots, contract_expiry, contracted_team, join_date, intl_games, intl_g, intl_a = scrape_player_page(link)
  File "<ipython-input-15-a36bb93fcbbf>", line 344, in scrape_player_page
    first_name, last_name = get_name(player_page)
  File "<ipython-input-15-a36bb93fcbbf>", line 16, in get_name
    name = name = player_page.find('div', class_='ep-entity-header__name').text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
Missing player information for: https://www.eliteprospects.com/player/343233/tomas-hrusik
Traceback (most recent call last):
  File "<ipython-input-17-0acbe3268e8d>", line 60, in scrape
    first_name, last_name, team, league, dob, birth_place, primary_nation, secondary_nation, declared_nation, position, height, weight, shoots, contract_expiry, contracted_team, join_date, intl_games, intl_g, intl_a = scrape_player_page(link)
  File "<ipython-input-15-a36bb93fcbbf>", line 344, in scrape_player_page
    first_name, last_name = get_name(player_page)
  File "<ipython-input-15-a36bb93fcbbf>", line 16, in get_name
    name = name = player_page.find('div', class_='ep-entity-header__name').text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
Missing player information for: https://www.eliteprospects.com/player/557412/daniel-kmosena
Traceback (most recent call last):
  File "<ipython-input-17-0acbe3268e8d>", line 60, in scrape
    first_name, last_name, team, league, dob, birth_place, primary_nation, secondary_nation, declared_nation, position, height, weight, shoots, contract_expiry, contracted_team, join_date, intl_games, intl_g, intl_a = scrape_player_page(link)
  File "<ipython-input-15-a36bb93fcbbf>", line 344, in scrape_player_page
    first_name, last_name = get_name(player_page)
  File "<ipython-input-15-a36bb93fcbbf>", line 16, in get_name
    name = name = player_page.find('div', class_='ep-entity-header__name').text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
Missing player information for: https://www.eliteprospects.com/player/653051/filip-kubiridzak

**Comment by xECK29x** [comment]
Working with latest code push!
