### ISSUE TITLE
Roster Scraper: Issue with duel-position players

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#28]
For players that are C/D, D/C, F/D or D/F the scraper is setting two 20 values. I would prefer to set a 20 value on the first position (C or LD/RD) and a 18 on the secondary (for F use Shoots side LW/RW).

Example player to test: https://www.eliteprospects.com/player.php?player=378568

**Comment by colinrsmall** [comment]
Fixed
