### ISSUE TITLE
Adding International Games to player details output sheets

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#3]
It would be a big help to also gather International game histories for players. These totals are kept in a table below the career history, simply add the International and International-Jr totals and place them in the appropriate rows (V, W, X). Goalies would only need games played.

Example player: https://www.eliteprospects.com/player/10472/jakub-cerny

**Comment by colinrsmall** [comment]
Fixed in 927ba3327e70b0c27d4abc4aa06ed94a19eb0b6a
