### ISSUE TITLE
Career History Scraper: Ability to only target specific seasons

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#31]
It would be great (and save a ton of time) to be able to specify a comma separated list of specific seasons to pull. For instance, I'm currently only focused on pulling in data from last year, but I have to wait for everything historically for all players to collect then I strip all the previous years out. This would speed up data collection and reduce wasted time removing the large amount of non-applicable data.

**Comment by colinrsmall** [comment]
Addressed in v2 of the history scraper
