### ISSUE TITLE
Roster Scraper: International Game Issue

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#36]
Looks like the scraper is having issues pulling international game totals, not only is the math not right its entering GP into GP and G fields with some while space which messes the whole sheet up. 

You can reproduce by running a scrape against any league/team with the toggle on, for instance see Marco Kasper's line here (also lots of missing of international games across this entire draft class as most have played in international tournaments):

leagues = "https://www.eliteprospects.com/draft/chl-import-draft/2022" #@param {type:"string"}
leagues = leagues.split(',')

season = "2022-23" #@param {type:"string"}
contract_expiry_prefix = "30.4.XXXX" #@param {type:"string"}
show_error_links = True #@param {type:"boolean"}
make_junior_contracts_to_age_20 = False #@param {type:"boolean"}
scrape_international_games = True #@param {type:"boolean"}
skip_players_with_blank_dobs = False #@param {type:"boolean"}
use_google_drive = False #@param {type:"boolean"}
calculate_remaining_eligible_years = False #@param {type:"boolean"}
override_contract_for_nhl_prospects = True #@param {type:"boolean"}
leagues_for_eligibility = "USports NCAA ACHA" #@param {type:"string"}
nhl_contracts = 'Skip players with NHL contracts' #@param ["Skip players with NHL contracts", "Include and set NHL team to playing", "Keep current team as playing"]

**Comment by colinrsmall** [comment]
Fixed
