### ISSUE TITLE
Blank entries with Roster Scrapper for club contracted/playing

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#7]
It's possible there was a subtle page redesign lately preventing scraping of current rosters to work correctly. I am getting blank entries to contracted/playing teams for 2021-22 rosters or for 2021 draft classes. See DIscord message https://discord.com/channels/@me/670943043972759573/858041992957132843 for an example. This can be reproduced on any-league/draft.

**Comment by colinrsmall** [comment]
Fixed in 784acf1
