### ISSUE TITLE
Roster Scraper: Contracts with player/team options

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#9]
For contracts with player/team options (extra years on top of the expiry date), please auto-calculate these to the maximum number of years. While 1.5 does support team/player options its a pain in the ass to do manually and no way to set them via the import sheets. I'd just opt for the maximum amount of years possible on a contract.

Example player: https://www.eliteprospects.com/player/24398/chay-genoway

**Comment by colinrsmall** [comment]
Scraper already does this, just make sure to leave "calculate_remaining_eligible_years" unchecked in the settings box, since that's only used for NCAA, uSports, etc.
